# Generated by Django 2.2.2 on 2019-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=64, unique=True)),
                ('content', models.FileField(upload_to='view_texts/')),
            ],
        ),
    ]
