# Generated by Django 2.2.2 on 2019-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewtext',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to='view_imgs/'),
        ),
        migrations.AddField(
            model_name='viewtext',
            name='title',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='viewtext',
            name='content',
            field=models.FileField(default='view_texts/default.txt', upload_to='view_texts/'),
        ),
    ]
