# Generated by Django 2.2.2 on 2019-06-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190618_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViewText',
            new_name='InfoViewTemplate',
        ),
    ]
