# Generated by Django 2.2.2 on 2019-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='menu_items/default.png', upload_to='menu_items/'),
        ),
    ]
