# Generated by Django 2.2.2 on 2019-06-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190617_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
