# Generated by Django 2.2.2 on 2019-06-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190621_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='active',
            new_name='available',
        ),
    ]
