# Generated by Django 2.2.3 on 2019-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190621_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(default='menu_specials/default.png', upload_to='menu_specials/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
